---
- name:
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Tear Down existing services
      docker_compose:
        project_src: /Users/gabrielrodriguez/repos/elk-dev-docker
        project_name: elk
        state: absent
    
    - name: Build and start services
      docker_compose:
        project_name: elk
        project_src: /Users/gabrielrodriguez/repos/elk-dev-docker
...